FC = caf
#FC = gfortran -fcoarray=single -ftree-parallelize-loops=4 -floop-parallelize-all
#FFLAGS = -Wall -O0 -g -fcheck=all
FFLAGS = -Wall -O3 -g

progs = $(basename $(wildcard *.f90))

all: $(progs)

%: %.f90 Makefile ~/lammps-velocityaverage/readers/reader.f90
	$(FC) $(FFLAGS) -o $@ ~/lammps-velocityaverage/readers/reader.f90 $<

clean:
	rm -rf *.dat $(progs) *.mod
